/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI Document on Azure Functions
 * This is the OpenAPI Document on Azure Functions
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  GetUploadSasUriParams,
  ResponseModel,
} from './openAPIDocumentOnAzureFunctions.schemas';

import { functionsApiMutator } from '../../axiosMutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getUploadSasUri = (
  params: GetUploadSasUriParams,
  options?: SecondParameter<typeof functionsApiMutator>,
  signal?: AbortSignal
) => {
  return functionsApiMutator<ResponseModel>(
    { url: `/GetUploadSasUri`, method: 'GET', params, signal },
    options
  );
};

export const getGetUploadSasUriQueryKey = (params: GetUploadSasUriParams) => {
  return [`/GetUploadSasUri`, ...(params ? [params] : [])] as const;
};

export const getGetUploadSasUriQueryOptions = <
  TData = Awaited<ReturnType<typeof getUploadSasUri>>,
  TError = string,
>(
  params: GetUploadSasUriParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUploadSasUri>>, TError, TData>>;
    request?: SecondParameter<typeof functionsApiMutator>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUploadSasUriQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUploadSasUri>>> = ({ signal }) =>
    getUploadSasUri(params, requestOptions, signal);

  return { queryKey, queryFn, staleTime: 10000, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUploadSasUri>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUploadSasUriQueryResult = NonNullable<Awaited<ReturnType<typeof getUploadSasUri>>>;
export type GetUploadSasUriQueryError = string;

export function useGetUploadSasUri<
  TData = Awaited<ReturnType<typeof getUploadSasUri>>,
  TError = string,
>(
  params: GetUploadSasUriParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUploadSasUri>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUploadSasUri>>,
          TError,
          Awaited<ReturnType<typeof getUploadSasUri>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof functionsApiMutator>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUploadSasUri<
  TData = Awaited<ReturnType<typeof getUploadSasUri>>,
  TError = string,
>(
  params: GetUploadSasUriParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUploadSasUri>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUploadSasUri>>,
          TError,
          Awaited<ReturnType<typeof getUploadSasUri>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof functionsApiMutator>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUploadSasUri<
  TData = Awaited<ReturnType<typeof getUploadSasUri>>,
  TError = string,
>(
  params: GetUploadSasUriParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUploadSasUri>>, TError, TData>>;
    request?: SecondParameter<typeof functionsApiMutator>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetUploadSasUri<
  TData = Awaited<ReturnType<typeof getUploadSasUri>>,
  TError = string,
>(
  params: GetUploadSasUriParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUploadSasUri>>, TError, TData>>;
    request?: SecondParameter<typeof functionsApiMutator>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetUploadSasUriQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
