/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI Document on Azure Functions
 * This is the OpenAPI Document on Azure Functions
 * OpenAPI spec version: 1.0.0
 */
export interface ReadSasResponseModel {
  blobFileName?: string;
  containerName?: string;
  readUri?: string;
}

export interface ResponseModel {
  originalFileName?: string;
  blobFileName?: string;
  uploadUri?: string;
}

export type GetReadSasUriParams = {
  /**
   * The name of the container (must be 'images' or 'recordings')
   */
  containerName: string;
  /**
   * The name of the blob file to access
   */
  blobFileName: string;
};

export type GetUploadSasUriParams = {
  /**
   * The name of the file to upload
   */
  fileName: string;
};
