# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Azure Function App - langapp-functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "./backend/LangApp/LangApp.Functions"
  DOTNET_VERSION: "9.x"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish Azure Functions project
        run: |
          pushd "$AZURE_FUNCTIONAPP_PACKAGE_PATH"
          dotnet publish -c Release -o output
          popd

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AD80B5495FEA419BBD8334AF511C5F01 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1874448E807E424EB709CA101321DE91 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_15A35A17B7194F10BCBE6975E7B0F662 }}

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: "langapp-functions"
          slot-name: "Production"
          package: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output"

