name: Build and deploy ASP.Net Core app to Azure Web App - langapp-webapp
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  SOLUTION_PATH: ./backend/LangApp/LangApp.sln
  API_PROJECT_PATH: ./backend/LangApp/LangApp.Api
  PUBLISH_DIR: publish
  AZURE_WEBAPP_PACKAGE_PATH: "./backend/LangApp/LangApp.Api/publish"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout
    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x"

      - name: Build with dotnet
        run: dotnet build ${{env.SOLUTION_PATH}} --configuration Release

      - name: Test
        run: dotnet test ${{env.SOLUTION_PATH}} --filter 'FullyQualifiedName!~Integration' --configuration Release --no-build --verbosity normal

      - name: dotnet publish
        working-directory: ${{env.API_PROJECT_PATH}}
        run: dotnet publish -c Release -o ${{env.PUBLISH_DIR}}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: webapp
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BE3F60994370430985BAEF3513CC8177 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3CBE0A6E7AF24F98A6CCFC9B6F4DA3D1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_98AAEE03BE6F44D98AADC674C4886E66 }}
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "langapp-webapp"
          slot-name: "Production"
          package: .
